name: update
on: 
  workflow_dispatch:
  schedule:
    - cron: '*01 * * * *'
    - cron: '*21 * * * *'
    - cron: '*41 * * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install bs4
  
    - name: Run script
      run: python fetch.py > nodes.txt
