name: update
on: 
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install bs4
  
    - name: Run script
      run: python fetch.py
    - name: submit changes
      run:
        git config --local user.email '${{ secrets.EMAIL }}'
        git config --local user.name '${{ secrets.NAME }}'
        git add ./nodes.txt
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        branch: main

    
